// miniapp/src/pages/hall/hall.vue
<template>
  <view class="hall-page">
    <!-- 搜索栏 -->
    <view class="search-bar">
      <input
        v-model="keyword"
        class="search-input"
        placeholder="搜索商机"
        confirm-type="search"
        @confirm="onSearch"
      />
      <text class="search-btn" @click="onSearch">搜索</text>
    </view>

    <!-- 分类筛选（横向滚动） -->
    <scroll-view scroll-x class="category-scroll">
      <view class="category-tabs">
        <view
          v-for="tab in categoryTabs"
          :key="tab.value"
          class="category-tab"
          :class="{ active: category === tab.value }"
          @click="selectCategory(tab.value)"
        >
          {{ tab.label }}
        </view>
      </view>
    </scroll-view>

    <!-- 排序 -->
    <view class="sort-bar">
      <view
        v-for="s in sortOptions"
        :key="s.value"
        class="sort-item"
        :class="{ active: sort === s.value }"
        @click="selectSort(s.value)"
      >
        {{ s.label }}
      </view>
    </view>

    <!-- 列表 -->
    <view class="list-wrap">
      <view v-if="loading && list.length === 0" class="empty">加载中...</view>
      <view v-else-if="list.length === 0" class="empty">暂无商机，换个分类或关键词试试</view>
      <view
        v-for="item in list"
        :key="item.id"
        class="opportunity-card"
        :class="{ purchased: item.isPurchased }"
        @click="goDetail(item.id)"
      >
        <view class="card-header">
          <view class="cat-badge">{{ CATEGORIES[item.categoryId] }}</view>
          <view class="card-info">
            <view class="card-title">
              <text v-if="item.isPurchased" class="purchased-tag">已购买</text>
              <text class="title-text">{{ item.title }}</text>
            </view>
            <view class="card-meta">
              <text class="meta-text">{{ item.hotelName || item.brand || '未知品牌' }} · {{ item.city || '未知城市' }}</text>
              <text v-if="item.stage" class="stage-tag" :class="stageTone(item.stage)">{{ stageLabel(item.stage) }}</text>
            </view>
          </view>
        </view>
        <view v-if="item.descriptionPublic" class="card-summary">{{ item.descriptionPublic }}</view>
        <view v-if="newShareCount(item) > 0" class="new-share-tip">
          {{ newShareCount(item) }} 条新共享跟进
        </view>
        <view class="heat-bar">
          <text class="heat-item heat-buy">{{ item.purchaseCount || 0 }}人已购</text>
          <text v-if="(item.totalShares || 0) > 0" class="heat-item heat-share">{{ item.totalShares }}条真实进度</text>
          <text class="heat-item">{{ item.viewCount || 0 }}次浏览</text>
        </view>
        <view class="card-footer">
          <view class="card-price">
            <text>{{ item.price }} 积分</text>
          </view>
          <view class="card-stats">
            <text class="card-time">{{ timeAgo(item.createdAt) }}</text>
          </view>
        </view>
      </view>
      <view v-if="!loading && hasMore" class="load-more" @click="loadMore">加载更多</view>
      <view v-if="!loading && !hasMore && list.length > 0" class="load-more">已经到底了</view>
    </view>
  </view>
</template>

<script setup>
import { ref, computed } from 'vue';
import { onLoad, onPullDownRefresh, onReachBottom } from '@dcloudio/uni-app';
import { api } from '@/api/index';
import { SUPPLIER_CATEGORIES, stageLabel, stageTone, timeAgo } from '@/common/constants';

const CATEGORIES = {};

SUPPLIER_CATEGORIES.forEach((c) => {
  CATEGORIES[c.value] = c.label;
});

const list = ref([]);
const loading = ref(false);
const refreshing = ref(false);
const keyword = ref('');
const category = ref('');
const sort = ref('newest');
const page = ref(1);
const hasMore = ref(true);

const categoryTabs = computed(() => [
  { label: '全部', value: '' },
  ...SUPPLIER_CATEGORIES.map((c) => ({ label: c.label, value: String(c.value) })),
]);

const sortOptions = [
  { label: '最新', value: 'newest' },
  { label: '最热', value: 'popular' },
  { label: '价格↑', value: 'price_asc' },
  { label: '价格↓', value: 'price_desc' },
];

async function fetchList(p = 1, reset = false) {
  try {
    const res = await api.opportunities({
      status: 'active',
      category: category.value || undefined,
      keyword: keyword.value || undefined,
      sort: sort.value,
      page: p,
      pageSize: 10,
    });
    const newList = res.list || [];
    list.value = reset ? newList : [...list.value, ...newList];
    hasMore.value = newList.length === 10;
    page.value = p;
  } catch (e) {
    uni.showToast({ title: e.message || '获取失败', icon: 'none' });
  } finally {
    loading.value = false;
    refreshing.value = false;
  }
}

async function reload() {
  loading.value = true;
  await fetchList(1, true);
}

function newShareCount(item) {
  if (!item.isPurchased) return 0;
  let viewed = 0;
  try {
    viewed = parseInt(uni.getStorageSync(`viewedShares_${item.id}`) || '0', 10) || 0;
  } catch (e) {
    viewed = 0;
  }
  return Math.max(0, (item.totalShares || 0) - viewed);
}

function selectCategory(value) {
  if (category.value === value) return;
  category.value = value;
  reload();
}

function selectSort(value) {
  if (sort.value === value) return;
  sort.value = value;
  reload();
}

function onSearch() {
  reload();
}

async function loadMore() {
  if (!loading.value && hasMore.value) {
    await fetchList(page.value + 1);
  }
}

function goDetail(id) {
  uni.navigateTo({ url: `/pages/opportunity/detail?id=${id}` });
}

onLoad(() => {
  reload();
});

onPullDownRefresh(async () => {
  refreshing.value = true;
  await reload();
  uni.stopPullDownRefresh();
});

onReachBottom(() => {
  loadMore();
});
</script>

<style lang="scss" scoped>
.hall-page {
  min-height: 100vh;
}

.search-bar {
  display: flex;
  align-items: center;
  padding: 16rpx 24rpx;
  background: #ffffff;
}

.search-input {
  flex: 1;
  height: 72rpx;
  line-height: 72rpx;
  padding: 0 24rpx;
  background: #F2F4F5;
  border-radius: 36rpx;
  font-size: 28rpx;
}

.search-btn {
  margin-left: 16rpx;
  color: #048C47;
  font-size: 28rpx;
}

.category-scroll {
  width: 100%;
  white-space: nowrap;
  background: #ffffff;
}

.category-tabs {
  display: inline-flex;
  padding: 12rpx 24rpx;
}

.category-tab {
  display: inline-block;
  padding: 12rpx 24rpx;
  margin-right: 16rpx;
  border-radius: 32rpx;
  font-size: 26rpx;
  color: #7A7A7A;
  background: #F2F4F5;
}

.category-tab.active {
  color: #ffffff;
  background: #048C47;
}

.sort-bar {
  display: flex;
  padding: 16rpx 24rpx;
  background: #ffffff;
  border-bottom: 1px solid #F2F4F5;
}

.sort-item {
  margin-right: 40rpx;
  font-size: 26rpx;
  color: #7A7A7A;
}

.sort-item.active {
  color: #048C47;
  font-weight: 600;
}

.list-wrap {
  padding: 16rpx 24rpx;
}

.opportunity-card {
  background: #ffffff;
  border-radius: 16rpx;
  padding: 24rpx;
  margin-bottom: 16rpx;
}

.opportunity-card.purchased {
  border: 1px solid #048C47;
}

.card-header {
  display: flex;
}

.cat-badge {
  width: 96rpx;
  height: 96rpx;
  border-radius: 16rpx;
  background: #E4F7EC;
  color: #048C47;
  font-size: 24rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 20rpx;
}

.card-info {
  flex: 1;
}

.card-title {
  font-size: 30rpx;
  font-weight: 600;
  color: #1A1A1A;
}

.purchased-tag {
  display: inline-block;
  margin-right: 8rpx;
  padding: 2rpx 12rpx;
  font-size: 20rpx;
  color: #ffffff;
  background: #048C47;
  border-radius: 8rpx;
}

.title-text {
  display: inline;
}

.card-meta {
  margin-top: 8rpx;
  display: flex;
  align-items: center;
}

.meta-text {
  font-size: 24rpx;
  color: #7A7A7A;
}

.stage-tag {
  margin-left: 12rpx;
  font-size: 20rpx;
  color: #7A7A7A;
  background: #F2F4F5;
  border-radius: 8rpx;
  padding: 2rpx 10rpx;
}

.stage-tag.hot {
  color: #E54848;
  background: #FDECEC;
}

.stage-tag.warm {
  color: #E8920A;
  background: #FFF4E0;
}

.stage-tag.verified {
  color: #048C47;
  background: #E4F7EC;
}

.card-summary {
  margin-top: 12rpx;
  font-size: 24rpx;
  color: #555555;
  line-height: 1.5;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
}

.new-share-tip {
  display: inline-block;
  margin-top: 12rpx;
  padding: 4rpx 14rpx;
  font-size: 22rpx;
  color: #E54848;
  background: #FDECEC;
  border-radius: 8rpx;
}

.heat-bar {
  margin-top: 12rpx;
  display: flex;
  align-items: center;
  font-size: 22rpx;
  color: #B0B0B0;
}

.heat-item {
  margin-right: 16rpx;
}

.heat-buy {
  color: #7A7A7A;
}

.heat-share {
  color: #048C47;
  font-weight: 600;
}

.card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 16rpx;
}

.card-price {
  font-size: 32rpx;
  color: #048C47;
  font-weight: 700;
}

.card-stats {
  display: flex;
  align-items: center;
}

.card-time {
  font-size: 22rpx;
  color: #B0B0B0;
}

.load-more {
  text-align: center;
  padding: 24rpx;
  color: #B0B0B0;
  font-size: 26rpx;
}

.empty {
  text-align: center;
  padding: 120rpx 0;
  color: #B0B0B0;
  font-size: 28rpx;
}
</style>

// archive/client/src/pages/Hall.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Tag, Toast, Search, PullRefresh, List } from 'react-vant';
import { api } from '../api';
import PageNavBar from '../components/PageNavBar';
import Icon from '../components/Icon';
import { SkeletonList } from '../components/StateView';
import { SUPPLIER_CATEGORIES, timeAgo, stageLabel, stageTone } from '../constants';
import { resolveCategoryIcon } from '../utils/category';

export default function Hall() {
  const navigate = useNavigate();
  const [list, setList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [keyword, setKeyword] = useState('');
  const [category, setCategory] = useState('');
  const [sort, setSort] = useState('newest');
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);

  const fetchList = async (p = 1, reset = false) => {
    try {
      const res = await api.opportunities({
        status: 'active',
        category: category || undefined,
        keyword: keyword || undefined,
        sort,
        page: p,
        pageSize: 10,
      });
      const newList = res.list || [];
      setList(reset ? newList : (prev) => [...prev, ...newList]);
      setHasMore(newList.length === 10);
      setPage(p);
    } catch (e) {
      Toast.fail(e.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    setLoading(true);
    fetchList(1, true);
  }, [category, sort]);

  const onRefresh = () => {
    setRefreshing(true);
    fetchList(1, true);
  };

  const loadMore = () => {
    if (!loading && hasMore) {
      fetchList(page + 1);
    }
  };

  const onSearch = () => {
    setLoading(true);
    fetchList(1, true);
  };

  const categoryTabs = [
    { title: '全部', value: '' },
    ...SUPPLIER_CATEGORIES.map((c) => ({ title: c.label, value: c.value })),
  ];

  return (
    <div className="page">
      <PageNavBar title="商机大厅" onClickLeft={() => navigate(-1)} />

      {/* 搜索栏 */}
      <Search
        value={keyword}
        onChange={setKeyword}
        onSearch={onSearch}
        placeholder="搜索商机"
        shape="round"
        className="search-bar"
      />

      {/* 分类筛选 */}
      <div className="category-tabs">
        {categoryTabs.map((tab) => (
          <span
            key={tab.value}
            className={`category-tab ${category === tab.value ? 'active' : ''}`}
            onClick={() => { setCategory(tab.value); setPage(1); }}
          >
            {tab.title}
          </span>
        ))}
      </div>

      {/* 排序 */}
      <div className="sort-bar">
        <span className={sort === 'newest' ? 'active' : ''} onClick={() => setSort('newest')}>最新</span>
        <span className={sort === 'popular' ? 'active' : ''} onClick={() => setSort('popular')}>最热</span>
        <span className={sort === 'price_asc' ? 'active' : ''} onClick={() => setSort('price_asc')}>
          价格<Icon name="ascending" size={12} />
        </span>
        <span className={sort === 'price_desc' ? 'active' : ''} onClick={() => setSort('price_desc')}>
          价格<Icon name="descending" size={12} />
        </span>
      </div>

      {/* 列表 */}
      <PullRefresh onRefresh={onRefresh} successDuration={500}>
        <List finished={!hasMore} onLoad={loadMore}>
          {loading && list.length === 0 ? (
            <SkeletonList count={4} />
          ) : list.length === 0 ? (
            <div className="state-empty">
              <div className="state-empty__title">暂无商机</div>
              <div className="state-empty__desc">换个分类或关键词试试</div>
            </div>
          ) : (
            list.map((item) => (
              <div
                className={`opportunity-card pressable ${item.isPurchased ? 'purchased' : ''}`}
                key={item.id}
                role="button"
                tabIndex={0}
                aria-label={`查看商机：${item.title}`}
                onClick={() => navigate(`/opportunity/${item.id}`)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    navigate(`/opportunity/${item.id}`);
                  }
                }}
              >
                <div className="opportunity-card__header">
                  <div className="cat-icon">
                    <Icon name={resolveCategoryIcon(item)} size={24} />
                  </div>
                  <div className="opportunity-card__info">
                    <div className="opportunity-card__title">
                      {item.isPurchased && (
                        <span className="opportunity-card__purchased-mark" aria-label="已购买">
                          <Icon name="success" size={11} color="#ffffff" />
                        </span>
                      )}
                      <span className="opportunity-card__title-text">{item.title}</span>
                      {item.isPurchased && <span className="opportunity-card__purchased-tag">已购买</span>}
                    </div>
                    <div className="opportunity-card__meta">
                      <span className="opportunity-card__meta-text">
                        {item.hotelName || item.brand || '未知品牌'} · {item.city || '未知城市'}
                      </span>
                      {item.stage && <span className={`opp-stage-tag ${stageTone(item.stage)}`}>{stageLabel(item.stage)}</span>}
                    </div>
                    {item.isPurchased && (() => {
                      try {
                        const viewed = parseInt(localStorage.getItem(`viewedShares_${item.id}`) || '0', 10);
                        const newCount = Math.max(0, (item.totalShares || 0) - viewed);
                        if (newCount > 0) {
                          return (
                            <div className="opportunity-card__new-share">
                              {newCount} 条新共享跟进
                            </div>
                          );
                        }
                      } catch {}
                      return null;
                    })()}
                  </div>
                </div>
                {item.descriptionPublic && (
                  <div className="opportunity-card__summary">{item.descriptionPublic}</div>
                )}
                <div className="opportunity-card__heat">
                  <span className="opportunity-card__heat-item opportunity-card__heat-item--buy">
                    {item.purchaseCount || 0}人已购
                  </span>
                  {(item.totalShares || 0) > 0 && (
                    <span className="opportunity-card__heat-item opportunity-card__heat-item--share">
                      {item.totalShares}条真实进度
                    </span>
                  )}
                  <span className="opportunity-card__heat-item">{item.viewCount || 0}次浏览</span>
                </div>
                <div className="opportunity-card__footer">
                  <div className="opportunity-card__price">
                    {item.isPurchased ? (
                      <>{item.price} 积分</>
                    ) : (
                      <>
                        <Icon name="lock" size={12} className="opportunity-card__lock-icon" />
                        {item.price} 积分
                      </>
                    )}
                  </div>
                  <div className="opportunity-card__stats">
                    <span className="opportunity-card__time">{timeAgo(item.createdAt)}</span>
                  </div>
                </div>
              </div>
            ))
          )}
        </List>
      </PullRefresh>
    </div>
  );
}
