// client/src/pages/Register.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Form, Input, Button, Picker, Toast, Cell } from 'react-vant';
import { useAuth } from '../context/AuthContext';
import { SUPPLIER_CATEGORIES } from '../constants';

export default function Register() {
  const navigate = useNavigate();
  const { register } = useAuth();
  const [submitting, setSubmitting] = useState(false);
  const [showPicker, setShowPicker] = useState(false);
  const [category, setCategory] = useState(SUPPLIER_CATEGORIES[0].value);

  const columns = SUPPLIER_CATEGORIES.map((c) => ({
    text: `${c.icon} ${c.label}`,
    value: c.value,
  }));

  const onFinish = async (values) => {
    setSubmitting(true);
    try {
      await register({ ...values, category });
      Toast.success('注册成功');
      navigate('/', { replace: true });
    } catch (e) {
      Toast.fail(e.message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-hero auth-hero--sm">
        <div className="auth-logo">注册账号</div>
        <p className="auth-slogan">加入酒店供应链互助生态</p>
      </div>

      <div className="auth-form">
        <Form
          onFinish={onFinish}
          footer={
            <Button type="primary" block round nativeType="submit" loading={submitting}>
              注册
            </Button>
          }
        >
          <Form.Item
            name="phone"
            label="手机号"
            rules={[
              { required: true, message: '请输入手机号' },
              { pattern: /^1\d{10}$/, message: '手机号格式不正确' },
            ]}
          >
            <Input type="tel" placeholder="请输入手机号" maxLength={11} />
          </Form.Item>
          <Form.Item
            name="nickname"
            label="昵称"
            rules={[{ required: true, message: '请填写昵称' }]}
          >
            <Input placeholder="如：装修张工" />
          </Form.Item>
          <Form.Item
            name="email"
            label="邮箱"
            rules={[
              { required: true, message: '请输入邮箱' },
              { pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/, message: '邮箱格式不正确' },
            ]}
          >
            <Input type="email" placeholder="用于找回密码" />
          </Form.Item>
          <Form.Item name="company" label="公司">
            <Input placeholder="公司名称（选填）" />
          </Form.Item>
          <Cell
            title="供应商类型"
            value={`${SUPPLIER_CATEGORIES.find((c) => c.value === category)?.icon} ${
              SUPPLIER_CATEGORIES.find((c) => c.value === category)?.label
            }`}
            isLink
            onClick={() => setShowPicker(true)}
          />
          <Form.Item
            name="password"
            label="密码"
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码至少 6 位' },
            ]}
          >
            <Input type="password" placeholder="至少 6 位密码" />
          </Form.Item>
        </Form>
        <div className="auth-link">
          已有账号？
          <Link to="/login">去登录</Link>
        </div>
        <div className="auth-agreement">
          注册即代表您已阅读并同意
          <Link to="/agreement/agreement">《用户协议》</Link>
          和
          <Link to="/agreement/privacy">《隐私政策》</Link>
        </div>
      </div>

      <Picker
        visible={showPicker}
        columns={columns}
        onConfirm={(value) => {
          if (value) setCategory(value);
          setShowPicker(false);
        }}
        onCancel={() => setShowPicker(false)}
      />
    </div>
  );
}

// miniapp/src/pages/login/register.vue
<template>
  <view class="register-page">
    <view class="register-hero">
      <view class="register-logo">注册账号</view>
      <view class="register-slogan">加入酒店供应链互助生态</view>
    </view>

    <view class="register-form">
      <view class="form-item">
        <text class="form-label">手机号</text>
        <input
          v-model="form.phone"
          type="tel"
          :maxlength="11"
          placeholder="请输入手机号"
          class="form-input"
        />
      </view>
      <view class="form-item">
        <text class="form-label">昵称</text>
        <input v-model="form.nickname" placeholder="如：装修张工" :maxlength="20" class="form-input" />
      </view>
      <view class="form-item">
        <text class="form-label">邮箱</text>
        <input v-model="form.email" type="email" placeholder="用于找回密码" class="form-input" />
      </view>
      <view class="form-item">
        <text class="form-label">公司（选填）</text>
        <input v-model="form.company" placeholder="公司名称" :maxlength="50" class="form-input" />
      </view>
      <picker mode="selector" :range="categoryLabels" :value="categoryIndex" @change="onCategoryChange">
        <view class="form-item">
          <text class="form-label">供应商类型</text>
          <view class="form-input form-picker">
            <text>{{ categoryLabel(form.category) }}</text>
            <text class="picker-arrow">›</text>
          </view>
        </view>
      </picker>
      <view class="form-item">
        <text class="form-label">密码</text>
        <view class="password-wrap">
          <input
            v-model="form.password"
            :type="passwordVisible ? 'text' : 'password'"
            placeholder="8 位以上，含字母和数字"
            :maxlength="32"
            class="form-input form-input--password"
          />
          <text class="password-toggle" @click="passwordVisible = !passwordVisible">
            {{ passwordVisible ? '隐藏' : '显示' }}
          </text>
        </view>
      </view>
      <view v-if="inviteCode" class="invite-tip">邀请码：{{ inviteCode }}</view>

      <button class="button-primary register-btn" :loading="submitting" :disabled="submitting" @click="handleRegister">
        {{ submitting ? '注册中...' : '注册' }}
      </button>
      <button class="register-link-btn" @click="goLogin">已有账号？去登录</button>

      <view class="register-agreement" @click="agreed = !agreed">
        <view class="agreement-box" :class="{ checked: agreed }">
          <text v-if="agreed" class="agreement-check">✓</text>
        </view>
        <text class="agreement-text">
          我已阅读并同意
          <text class="link" @click.stop="goAgreement('agreement')">《用户协议》</text>
          和
          <text class="link" @click.stop="goAgreement('privacy')">《隐私政策》</text>
        </text>
      </view>
    </view>
  </view>
</template>

<script setup>
import { computed, reactive, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { useUserStore } from '@/store/user';
import { SUPPLIER_CATEGORIES, categoryLabel } from '@/common/constants';

const userStore = useUserStore();

const submitting = ref(false);
const passwordVisible = ref(false);
const agreed = ref(false);
const inviteCode = ref('');
const categoryLabels = SUPPLIER_CATEGORIES.map((c) => c.label);

const form = reactive({
  phone: '',
  nickname: '',
  email: '',
  company: '',
  category: SUPPLIER_CATEGORIES[0].value,
  password: '',
});

const categoryIndex = computed(() => {
  const idx = SUPPLIER_CATEGORIES.findIndex((c) => c.value === form.category);
  return idx >= 0 ? idx : 0;
});

onLoad((options) => {
  // 分享卡片/邀请页携带邀请码优先，其次消费登录页暂存
  const fromParam = options && options.inviteCode;
  const fromStorage = uni.getStorageSync('hof_pending_invite') || '';
  inviteCode.value = fromParam || fromStorage;
});

async function handleRegister() {
  if (!agreed.value) {
    uni.showToast({ title: '请先阅读并同意用户协议和隐私政策', icon: 'none' });
    return;
  }
  if (!/^1\d{10}$/.test(form.phone)) {
    uni.showToast({ title: '请输入正确手机号', icon: 'none' });
    return;
  }
  if (!form.nickname.trim()) {
    uni.showToast({ title: '请填写昵称', icon: 'none' });
    return;
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) {
    uni.showToast({ title: '请输入正确邮箱', icon: 'none' });
    return;
  }
  if (!/^(?=.*[a-zA-Z])(?=.*\d).{8,}$/.test(form.password)) {
    uni.showToast({ title: '密码至少 8 位，且必须包含字母和数字', icon: 'none' });
    return;
  }
  if (submitting.value) return;
  submitting.value = true;
  try {
    await userStore.register({
      phone: form.phone,
      password: form.password,
      nickname: form.nickname.trim(),
      email: form.email.trim(),
      company: form.company.trim(),
      category: form.category,
      inviteCode: inviteCode.value || undefined,
    });
    uni.removeStorageSync('hof_pending_invite');
    uni.showToast({ title: '注册成功', icon: 'success' });
    setTimeout(() => {
      uni.reLaunch({ url: '/pages/index/index' });
    }, 800);
  } catch (e) {
    uni.showToast({ title: e.message || '注册失败', icon: 'none' });
  } finally {
    submitting.value = false;
  }
}

function goLogin() {
  uni.navigateBack();
}

function onCategoryChange(e) {
  const idx = Number(e.detail.value);
  const selected = SUPPLIER_CATEGORIES[idx];
  if (selected) form.category = selected.value;
}

function goAgreement(type) {
  uni.navigateTo({ url: `/pages/common/agreement?type=${type}` });
}
</script>

<style lang="scss" scoped>
.register-page {
  min-height: 100vh;
  background: #ffffff;
  display: flex;
  flex-direction: column;
}

.register-hero {
  padding: 80rpx 60rpx 60rpx;
  background: linear-gradient(135deg, #048C47 0%, #036B38 100%);
  color: #ffffff;
}

.register-logo {
  font-size: 48rpx;
  font-weight: 700;
  text-align: center;
}

.register-slogan {
  margin-top: 16rpx;
  font-size: 26rpx;
  text-align: center;
  opacity: 0.9;
}

.register-form {
  padding: 40rpx 60rpx;
}

.form-item {
  margin-bottom: 24rpx;
}

.form-label {
  display: block;
  font-size: 24rpx;
  color: #7A7A7A;
  margin-bottom: 8rpx;
}

.form-input {
  height: 88rpx;
  line-height: 88rpx;
  padding: 0 20rpx;
  background: #F2F4F5;
  border-radius: 12rpx;
  font-size: 28rpx;
}

.form-picker {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.password-wrap {
  position: relative;
}

.form-input--password {
  padding-right: 120rpx;
}

.password-toggle {
  position: absolute;
  right: 0;
  top: 0;
  height: 88rpx;
  line-height: 88rpx;
  padding: 0 24rpx;
  font-size: 26rpx;
  color: #048C47;
}

.picker-arrow {
  color: #B0B0B0;
  font-size: 32rpx;
}

.invite-tip {
  font-size: 24rpx;
  color: #048C47;
  margin-bottom: 16rpx;
}

.register-btn {
  margin-top: 32rpx;
  width: 100%;
}

.register-link-btn {
  margin-top: 16rpx;
  width: 100%;
  border: none;
  background: transparent;
  color: #048C47;
  font-size: 28rpx;
}

.register-agreement {
  margin-top: 40rpx;
  display: flex;
  align-items: flex-start;
  padding: 12rpx 8rpx;
}

.agreement-box {
  flex-shrink: 0;
  width: 36rpx;
  height: 36rpx;
  margin-right: 12rpx;
  border: 1px solid #C0C4C8;
  border-radius: 6rpx;
  background: #ffffff;
  text-align: center;
  line-height: 34rpx;
}

.agreement-box.checked {
  border-color: #048C47;
  background: #048C47;
}

.agreement-check {
  font-size: 24rpx;
  color: #ffffff;
}

.agreement-text {
  flex: 1;
  font-size: 24rpx;
  color: #555555;
  line-height: 36rpx;
}

.link {
  color: #048C47;
}
</style>
