// miniapp/src/pages/community/invite.vue
<template>
  <view class="invite-page">
    <view v-if="loading" class="empty">加载中...</view>
    <template v-else>
      <!-- 邀请码卡片 -->
      <view class="invite-card">
        <view class="invite-card__label">我的邀请码</view>
        <view class="invite-card__code">{{ data?.inviteCode || '暂无' }}</view>
        <button class="invite-btn" size="small" round @click="handleCopy">复制邀请码</button>
      </view>

      <!-- 邀请奖励说明 -->
      <view class="section-card">
        <view class="reward-row"><text class="reward-text">邀请奖励</text><text class="reward-desc">邀请人和被邀请人各得 5 积分</text></view>
        <view class="reward-row"><text class="reward-text">已邀请人数</text><text class="reward-num">{{ data?.stats?.totalInvited || 0 }}</text></view>
        <view class="reward-row"><text class="reward-text">累计奖励</text><text class="reward-num">{{ data?.stats?.totalReward || 0 }} 积分</text></view>
      </view>

      <!-- 分享小程序给好友 -->
      <view class="section-card share-card">
        <view class="share-tip">邀请好友注册，双方各得 5 积分</view>
        <button class="invite-btn invite-btn--primary" size="small" round open-type="share">
          分享给微信好友
        </button>
      </view>

      <!-- 邀请记录 -->
      <view class="section-title">邀请记录</view>
      <view class="section-card">
        <view v-if="!data?.records?.length" class="empty">暂无邀请记录</view>
        <view v-else class="record-list">
          <view v-for="record in visibleRecords" :key="record.id" class="record-item">
            <view class="record-info">
              <view class="record-user">{{ record.invitee_nickname || '新用户' }}</view>
              <view class="record-time">{{ timeAgo(record.created_at) }}</view>
            </view>
            <text class="record-reward">+{{ record.inviter_reward }} 积分</text>
          </view>
        </view>
        <view v-if="totalPages > 1" class="pager">
          <view class="pager-btn" :class="{ disabled: page <= 1 }" @click="changePage(page - 1)">上一页</view>
          <view class="pager-info">{{ page }} / {{ totalPages }}</view>
          <view class="pager-btn" :class="{ disabled: page >= totalPages }" @click="changePage(page + 1)">下一页</view>
        </view>
      </view>
    </template>
  </view>
</template>

<script setup>
import { ref, computed } from 'vue';
import { onLoad, onShareAppMessage } from '@dcloudio/uni-app';
import { api } from '@/api/index';
import { timeAgo } from '@/common/constants';

const loading = ref(true);
const data = ref(null);
const page = ref(1);
const pageSize = 6;

onLoad(() => {
  api.invitationMe()
    .then((res) => {
      data.value = res || null;
    })
    .catch(() => {})
    .finally(() => {
      loading.value = false;
    });
});

onShareAppMessage(() => {
  const code = data.value?.inviteCode || '';
  return {
    title: '商机互助：邀请你来一起赚积分',
    path: `/pages/login/index?inviteCode=${code}`,
  };
});

const totalPages = computed(() =>
  Math.ceil((data.value?.records || []).length / pageSize)
);

const visibleRecords = computed(() => {
  const records = data.value?.records || [];
  const start = (page.value - 1) * pageSize;
  return records.slice(start, start + pageSize);
});

function handleCopy() {
  const code = data.value?.inviteCode;
  if (!code) {
    uni.showToast({ title: '暂无邀请码', icon: 'none' });
    return;
  }
  uni.setClipboardData({
    data: code,
    success: () => {
      uni.showToast({ title: '邀请码已复制', icon: 'success' });
    },
  });
}

function changePage(p) {
  if (p < 1 || p > totalPages.value) return;
  page.value = p;
}
</script>

<style lang="scss" scoped>
.invite-page {
  min-height: 100vh;
}

.empty {
  text-align: center;
  padding: 80rpx 0;
  color: #B0B0B0;
  font-size: 28rpx;
}

.invite-card {
  margin: 24rpx;
  background: linear-gradient(135deg, #048C47 0%, #036B38 100%);
  border-radius: 16rpx;
  padding: 48rpx 40rpx;
  text-align: center;
  color: #ffffff;
}

.invite-card__label {
  font-size: 26rpx;
  opacity: 0.9;
}

.invite-card__code {
  margin-top: 16rpx;
  font-size: 56rpx;
  font-weight: 700;
  letter-spacing: 8rpx;
}

.invite-btn {
  margin-top: 32rpx;
  padding: 0 48rpx;
  background: #ffffff;
  color: #048C47;
  border: none;
  font-size: 26rpx;
}

.invite-btn--primary {
  background: #048C47;
  color: #ffffff;
}

.section-card {
  margin: 0 24rpx 16rpx;
  background: #ffffff;
  border-radius: 16rpx;
  padding: 24rpx;
}

.section-title {
  margin: 8rpx 32rpx 16rpx;
  font-size: 28rpx;
  font-weight: 600;
  color: #1A1A1A;
}

.reward-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14rpx 0;
}

.reward-text {
  font-size: 26rpx;
  color: #4A4A4A;
}

.reward-desc {
  font-size: 26rpx;
  color: #1A1A1A;
}

.reward-num {
  font-size: 26rpx;
  color: #048C47;
  font-weight: 600;
}

.share-card {
  text-align: center;
}

.share-tip {
  font-size: 26rpx;
  color: #4A4A4A;
}

.record-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 18rpx 0;
  border-bottom: 1px solid #F2F4F5;
}

.record-item:last-child {
  border-bottom: none;
}

.record-user {
  font-size: 26rpx;
  color: #1A1A1A;
}

.record-time {
  margin-top: 6rpx;
  font-size: 22rpx;
  color: #B0B0B0;
}

.record-reward {
  font-size: 28rpx;
  color: #048C47;
  font-weight: 600;
}

.pager {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24rpx 0 8rpx;
}

.pager-btn {
  padding: 10rpx 32rpx;
  border-radius: 8rpx;
  border: 1px solid #048C47;
  color: #048C47;
  font-size: 24rpx;
}

.pager-btn.disabled {
  opacity: 0.4;
}

.pager-info {
  margin: 0 24rpx;
  font-size: 24rpx;
  color: #7A7A7A;
}
</style>

// client/src/pages/Invite.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { NavBar, Toast, Button, Cell, CellGroup, Empty, Tabs } from 'react-vant';
import { api } from '../api';
import { timeAgo } from '../constants';
import InvitePoster from '../components/InvitePoster';
import { ArrowLeft, GiftO } from '@react-vant/icons';

export default function Invite() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [nickname, setNickname] = useState('');
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState('code');

  useEffect(() => {
    api.invitationMe()
      .then(setData)
      .catch((e) => Toast.fail(e.message))
      .finally(() => setLoading(false));
    api.me()
      .then((me) => setNickname(me?.nickname || '酒店跟单伙伴'))
      .catch(() => {});
  }, []);

  const handleCopy = () => {
    if (data?.inviteCode) {
      navigator.clipboard.writeText(data.inviteCode)
        .then(() => Toast.success('邀请码已复制'))
        .catch(() => Toast.fail('复制失败'));
    }
  };

  if (loading) return <div className="empty-tip">加载中...</div>;

  return (
    <div className="page">
      <NavBar title="邀请好友" leftArrow={<ArrowLeft width={20} height={20} />} onClickLeft={() => navigate(-1)} safeAreaInsetTop />

      {/* 邀请码 */}
      <div className="invite-card">
        <div className="invite-card__label">我的邀请码</div>
        <div className="invite-card__code">{data?.inviteCode || '暂无'}</div>
        <Button type="primary" round onClick={handleCopy}>复制邀请码</Button>
      </div>

      {/* 海报 */}
      <div className="section" style={{ padding: '12px 16px' }}>
        <div className="section-title">邀请海报</div>
        <Tabs value={tab} onChange={setTab}>
          <Tabs.TabPane title="邀请码" name="code" />
          <Tabs.TabPane title="海报" name="poster" />
        </Tabs>
        {tab === 'poster' && <InvitePoster inviteCode={data?.inviteCode} nickname={nickname} />}
      </div>

      {/* 邀请奖励说明 */}
      <CellGroup inset style={{ marginTop: 12 }}>
        <Cell title="邀请奖励" label="邀请人和被邀请人各得5积分" icon={<GiftO width={20} height={20} />} />
        <Cell title="已邀请人数" value={data?.stats?.totalInvited || 0} />
        <Cell title="累计奖励" value={`${data?.stats?.totalReward || 0} 积分`} />
      </CellGroup>

      {/* 邀请记录 */}
      <div className="section" style={{ padding: '12px 16px' }}>
        <div className="section-title">邀请记录</div>
        {data?.records?.length > 0 ? (
          data.records.map((record) => (
            <div key={record.id} className="invite-record">
              <div className="invite-record__user">{record.invitee_nickname || '新用户'}</div>
              <div className="invite-record__time">{timeAgo(record.created_at)}</div>
              <div className="invite-record__reward">+{record.inviter_reward} 积分</div>
            </div>
          ))
        ) : (
          <Empty description="暂无邀请记录" />
        )}
      </div>
    </div>
  );
}
