// miniapp/src/pages/community/ranking.vue
<template>
  <view class="ranking-page">
    <!-- Tab 切换 -->
    <view class="rank-tabs">
      <view
        v-for="t in tabs"
        :key="t.name"
        class="rank-tab"
        :class="{ active: type === t.name }"
        @click="switchType(t.name)"
      >
        {{ t.title }}
      </view>
    </view>

    <view v-if="loading" class="empty">加载中...</view>
    <view v-else-if="!list.length" class="empty">暂无排行数据</view>
    <view v-else class="rank-list">
      <view v-for="item in visible" :key="item.id" class="rank-item">
        <view class="rank-no" :class="{ 'rank-no--top': item.rank <= 3 }">{{ item.rank }}</view>
        <view class="rank-avatar">{{ item.nickname?.[0] || '匿' }}</view>
        <view class="rank-info">
          <view class="rank-name">{{ item.nickname || '匿名用户' }}</view>
          <view class="rank-score">
            {{ type === 'publisher' ? `${item.purchase_count || 0} 次购买` : `${item.helpful_count || 0} 次有用` }}
          </view>
        </view>
      </view>
      <view v-if="totalPages > 1" class="pager">
        <view class="pager-btn" :class="{ disabled: page <= 1 }" @click="changePage(page - 1)">上一页</view>
        <view class="pager-info">{{ page }} / {{ totalPages }}</view>
        <view class="pager-btn" :class="{ disabled: page >= totalPages }" @click="changePage(page + 1)">下一页</view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, computed } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api } from '@/api/index';

const tabs = [
  { title: '商机达人榜', name: 'publisher' },
  { title: '贡献榜', name: 'contributor' },
];

const type = ref('publisher');
const list = ref([]);
const loading = ref(true);
const page = ref(1);
const pageSize = 6;

onLoad(() => {
  fetchRank();
});

function switchType(name) {
  if (type.value === name) return;
  type.value = name;
  page.value = 1;
  fetchRank();
}

async function fetchRank() {
  loading.value = true;
  page.value = 1;
  try {
    const res = await api.rankings({ type: type.value, pageSize: 50 });
    list.value = res?.list || [];
  } catch (e) {
    list.value = [];
    uni.showToast({ title: e.message || '加载失败', icon: 'none' });
  } finally {
    loading.value = false;
    uni.stopPullDownRefresh();
  }
}

const totalPages = computed(() => Math.ceil(list.value.length / pageSize));
const visible = computed(() => {
  const start = (page.value - 1) * pageSize;
  return list.value.slice(start, start + pageSize);
});

function changePage(p) {
  if (p < 1 || p > totalPages.value) return;
  page.value = p;
}
</script>

<style lang="scss" scoped>
.ranking-page {
  min-height: 100vh;
}

.rank-tabs {
  display: flex;
  background: #ffffff;
  padding: 0 24rpx;
}

.rank-tab {
  position: relative;
  padding: 24rpx 32rpx;
  font-size: 28rpx;
  color: #7A7A7A;
}

.rank-tab.active {
  color: #048C47;
  font-weight: 600;
}

.rank-tab.active::after {
  content: '';
  position: absolute;
  left: 50%;
  bottom: 0;
  transform: translateX(-50%);
  width: 40rpx;
  height: 6rpx;
  border-radius: 3rpx;
  background: #048C47;
}

.empty {
  text-align: center;
  padding: 120rpx 0;
  color: #B0B0B0;
  font-size: 28rpx;
}

.rank-list {
  padding: 0 24rpx;
}

.rank-item {
  display: flex;
  align-items: center;
  background: #ffffff;
  border-radius: 16rpx;
  margin-top: 16rpx;
  padding: 24rpx;
}

.rank-no {
  width: 56rpx;
  height: 56rpx;
  line-height: 56rpx;
  text-align: center;
  border-radius: 50%;
  background: #F2F4F5;
  color: #7A7A7A;
  font-size: 28rpx;
  font-weight: 700;
}

.rank-no--top {
  background: #E8920A;
  color: #ffffff;
}

.rank-avatar {
  width: 72rpx;
  height: 72rpx;
  line-height: 72rpx;
  text-align: center;
  border-radius: 50%;
  background: #E4F7EC;
  color: #048C47;
  font-size: 30rpx;
  margin-left: 20rpx;
}

.rank-info {
  margin-left: 20rpx;
}

.rank-name {
  font-size: 28rpx;
  color: #1A1A1A;
}

.rank-score {
  margin-top: 6rpx;
  font-size: 24rpx;
  color: #7A7A7A;
}

.pager {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24rpx 0 8rpx;
}

.pager-btn {
  padding: 10rpx 32rpx;
  border-radius: 8rpx;
  border: 1px solid #048C47;
  color: #048C47;
  font-size: 24rpx;
}

.pager-btn.disabled {
  opacity: 0.4;
}

.pager-info {
  margin: 0 24rpx;
  font-size: 24rpx;
  color: #7A7A7A;
}
</style>

// client/src/pages/Ranking.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { NavBar, Toast, Tabs, Empty } from 'react-vant';
import { api } from '../api';
import { ArrowLeft } from '@react-vant/icons';

export default function Ranking() {
  const navigate = useNavigate();
  const [type, setType] = useState('publisher');
  const [list, setList] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    api.rankings({ type, pageSize: 20 })
      .then((res) => setList(res.list || []))
      .catch((e) => Toast.fail(e.message))
      .finally(() => setLoading(false));
  }, [type]);

  return (
    <div className="page">
      <NavBar title="排行榜" leftArrow={<ArrowLeft width={20} height={20} />} onClickLeft={() => navigate(-1)} safeAreaInsetTop />

      <Tabs value={type} onChange={setType}>
        <Tabs.TabPane title="跟单达人榜" name="publisher" />
        <Tabs.TabPane title="贡献榜" name="contributor" />
      </Tabs>

      {loading ? (
        <div className="empty-tip">加载中...</div>
      ) : list.length === 0 ? (
        <Empty description="暂无排行数据" style={{ marginTop: 40 }} />
      ) : (
        <div className="ranking-list">
          {list.map((item) => (
            <div className="ranking-item" key={item.id}>
              <div className={`ranking-item__rank ${item.rank <= 3 ? 'top' : ''}`}>
                {item.rank}
              </div>
              <div className="ranking-item__avatar">{item.nickname?.[0] || '匿'}</div>
              <div className="ranking-item__info">
                <div className="ranking-item__name">{item.nickname || '匿名用户'}</div>
                <div className="ranking-item__score">
                  {type === 'publisher' ? `${item.purchase_count || 0} 次购买` : `${item.helpful_count || 0} 次有用`}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
