// miniapp/src/pages/admin/dashboard.vue
<template>
  <view class="dash-page">
    <view v-if="loading" class="empty">加载中...</view>
    <view v-else>
      <view class="stat-grid">
        <view v-for="card in statCards" :key="card.title" class="stat-card">
          <view class="stat-title">{{ card.title }}</view>
          <view class="stat-value" :style="{ color: card.color }">{{ card.value }}</view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import { adminApi } from '@/admin/adminApi';

const stats = ref(null);
const loading = ref(true);

const statCards = [
  { title: '用户总数', key: 'totalUsers', color: '#048C47' },
  { title: '商机总数', key: 'totalOpportunities', color: '#048C47' },
  { title: '订单总数', key: 'totalOrders', color: '#E8920A' },
  { title: '积分总量', key: 'totalPoints', color: '#E54848' },
];

async function load() {
  loading.value = true;
  try {
    stats.value = await adminApi.getDashboard();
  } catch (e) {
    uni.showToast({ title: e.message || '获取失败', icon: 'none' });
  } finally {
    loading.value = false;
  }
}

onShow(load);
</script>

<style lang="scss" scoped>
.dash-page {
  min-height: 100vh;
  background: #F2F4F5;
  padding: 24rpx;
}
.stat-grid {
  display: flex;
  flex-wrap: wrap;
}
.stat-card {
  width: 48%;
  margin-bottom: 16rpx;
  background: #ffffff;
  border-radius: 16rpx;
  padding: 32rpx 24rpx;
}
.stat-card:nth-child(odd) {
  margin-right: 4%;
}
.stat-title {
  font-size: 26rpx;
  color: #7A7A7A;
  margin-bottom: 16rpx;
}
.stat-value {
  font-size: 48rpx;
  font-weight: 600;
}
</style>

// archive/client/src/pages/admin/Dashboard.jsx
import { useState, useEffect } from 'react';
import { Card, Row, Col, Statistic, Table, Typography } from 'antd';
import { UserOutlined, FileTextOutlined, OrderedListOutlined, CreditCardOutlined } from '@ant-design/icons';
import { adminApi } from '../../admin/api';

const { Title } = Typography;

export default function Dashboard() {
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    adminApi.getDashboard()
      .then(setStats)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const statCards = [
    { title: '用户总数', value: stats?.totalUsers || 0, icon: <UserOutlined />, color: '#048C47' },
    { title: '商机总数', value: stats?.totalOpportunities || 0, icon: <FileTextOutlined />, color: '#048C47' },
    { title: '订单总数', value: stats?.totalOrders || 0, icon: <OrderedListOutlined />, color: '#E8920A' },
    { title: '积分总量', value: stats?.totalPoints || 0, icon: <CreditCardOutlined />, color: '#E54848' },
  ];

  return (
    <div>
      <Title level={4}>仪表盘</Title>
      <Row gutter={16} style={{ marginBottom: 24 }}>
        {statCards.map((card, index) => (
          <Col span={6} key={index}>
            <Card>
              <Statistic
                title={card.title}
                value={card.value}
                prefix={card.icon}
                valueStyle={{ color: card.color }}
              />
            </Card>
          </Col>
        ))}
      </Row>
    </div>
  );
}
