// client/src/pages/Profile.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { NavBar, Cell, CellGroup, Tag, ActionSheet, Dialog } from 'react-vant';
import Icon from '../components/Icon';
import { useAuth } from '../context/AuthContext';
import { levelMeta, categoryLabel } from '../constants';

export default function Profile() {
  const navigate = useNavigate();
  const { user, logout, refreshUser } = useAuth();
  const [showAgreements, setShowAgreements] = useState(false);

  useEffect(() => {
    refreshUser().catch(() => {});
  }, []);

  const level = levelMeta(user?.level || 'normal');

  const handleLogout = () => {
    Dialog.confirm({
      title: '退出登录',
      message: '确认退出当前账号？',
    }).then(() => {
      logout();
      navigate('/login');
    }).catch(() => {});
  };

  return (
    <div className="page">
      <NavBar title="个人中心" safeAreaInsetTop />

      {/* 用户信息卡片 */}
      <div className="profile-card">
        <div className="profile-card__avatar">{user?.nickname?.[0] || '友'}</div>
        <div className="profile-card__info">
          <div className="profile-card__name">{user?.nickname || '未登录'}</div>
          <Tag className="profile-card__level-tag">{level.label}</Tag>
        </div>
        <div className="profile-card__credit">
          信用分：
          <span className="profile-card__credit-val">
            {user?.creditScore || 100}
          </span>
        </div>
      </div>

      {/* 联系/身份信息 */}
      <div className="profile-meta profile-meta--gap">
        {user?.company && (
          <div className="profile-meta__item"><span>公司</span>{user.company}</div>
        )}
        {user?.category != null && (
          <div className="profile-meta__item"><span>类型</span>{categoryLabel(user.category)}</div>
        )}
        {user?.email && (
          <div className="profile-meta__item"><span>邮箱</span>{user.email}</div>
        )}
      </div>

      {/* 积分快捷入口 */}
      <div className="profile-points pressable" onClick={() => navigate('/points')}>
        <span>我的积分</span>
        <span className="profile-points__num">{user?.pointsBalance ?? 0}</span>
      </div>

      {/* 资质展示 */}
      {user?.qualifications && (
        <div className="section">
          <div className="section-title">专业资质</div>
          <div className="qualification-list">
            {user.qualifications.split('\n').filter(Boolean).map((q, i) => (
              <div key={i} className="qualification-item">
                <Icon name="certificate" size={16} color="var(--primary-color)" />
                <span>{q}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 案例展示 */}
      {user?.cases && (
        <div className="section">
          <div className="section-title">典型案例</div>
          <div className="case-list">
            {user.cases.split('\n').filter(Boolean).map((c, i) => (
              <div key={i} className="case-card">
                <div className="case-card__desc">{c}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 功能列表 */}
      <CellGroup inset>
        <Cell title="积分中心" isLink onClick={() => navigate('/points')} icon={<Icon name="gold-coin-o" size={18} />} />
        <Cell title="会员等级" isLink onClick={() => navigate('/member-level')} icon={<Icon name="award-o" size={18} />} />
        <Cell title="信用分" isLink onClick={() => navigate('/credit')} icon={<Icon name="shield-o" size={18} />} />
        <Cell title="邀请好友" isLink onClick={() => navigate('/invite')} icon={<Icon name="friends-o" size={18} />} />
        <Cell title="排行榜" isLink onClick={() => navigate('/ranking')} icon={<Icon name="medal-o" size={18} />} />
        <Cell title="通知中心" isLink onClick={() => navigate('/notifications')} icon={<Icon name="bell" size={18} />} />
        <Cell title="提醒中心" isLink onClick={() => navigate('/reminders')} icon={<Icon name="alarm-o" size={18} />} />
      </CellGroup>

      {/* 设置 */}
      <CellGroup inset className="profile-section--gap">
        <Cell title="编辑资料" isLink onClick={() => navigate('/profile/edit')} icon={<Icon name="edit" size={18} />} />
        <Cell title="账号安全" isLink onClick={() => navigate('/profile/change-password')} icon={<Icon name="lock" size={18} />} />
        <Cell title="客服与帮助" isLink onClick={() => navigate('/support')} icon={<Icon name="service-o" size={18} />} />
        <Cell title="用户协议与隐私" isLink onClick={() => setShowAgreements(true)} icon={<Icon name="notes-o" size={18} />} />
        <Cell title="退出登录" onClick={handleLogout} icon={<Icon name="close" size={18} />} />
      </CellGroup>

      <div className="profile-footer-space" />

      <ActionSheet
        visible={showAgreements}
        actions={[
          { name: '用户协议', key: 'agreement' },
          { name: '隐私政策', key: 'privacy' },
          { name: '平台须知', key: 'summary' },
        ]}
        onSelect={(action) => {
          setShowAgreements(false);
          navigate(`/agreement/${action.key}`);
        }}
        onCancel={() => setShowAgreements(false)}
      />
    </div>
  );
}

// miniapp/src/pages/profile/index.vue
<template>
  <view class="profile-page">
    <!-- 用户信息卡片 -->
    <view class="profile-card">
      <view class="avatar">{{ user?.nickname?.[0] || '友' }}</view>
      <view class="profile-info">
        <view class="profile-name">{{ user?.nickname || '未登录' }}</view>
        <text class="level-tag" :style="levelStyle">{{ level.label }}</text>
      </view>
      <view class="credit">
        信用分：
        <text class="credit-val">{{ user?.creditScore || 100 }}</text>
      </view>
    </view>

    <!-- 联系/身份信息 + 积分入口 -->
    <view class="profile-meta">
      <view v-if="user?.company" class="meta-item">
        <text class="meta-label">公司</text>
        <text class="meta-value">{{ user.company }}</text>
      </view>
      <view v-if="user?.category != null" class="meta-item">
        <text class="meta-label">类型</text>
        <text class="meta-value">{{ categoryLabel(user.category) }}</text>
      </view>
      <view v-if="user?.email" class="meta-item">
        <text class="meta-label">邮箱</text>
        <text class="meta-value">{{ user.email }}</text>
      </view>
      <view class="meta-item meta-item--link" @click="goPoints">
        <text class="meta-label">我的积分</text>
        <view class="points-num">
          <text class="points-val">{{ user?.pointsBalance ?? 0 }}</text>
          <text class="arrow">›</text>
        </view>
      </view>
    </view>

    <!-- 资质展示 -->
    <view v-if="qualifications.length" class="section-card">
      <view class="section-title">专业资质</view>
      <view v-for="(q, i) in qualifications" :key="i" class="qualification-item">
        <text class="section-mark">✔</text>
        <text class="qualification-text">{{ q }}</text>
      </view>
    </view>

    <!-- 案例展示 -->
    <view v-if="cases.length" class="section-card">
      <view class="section-title">典型案例</view>
      <view v-for="(c, i) in cases" :key="i" class="case-card">
        <text class="case-text">{{ c }}</text>
      </view>
    </view>

    <!-- 功能列表 -->
    <view class="func-card">
      <view v-for="item in funcList" :key="item.title" class="func-row" @click="onFunc(item)">
        <text class="func-title">{{ item.title }}</text>
        <text class="arrow">›</text>
      </view>
    </view>

    <!-- 设置 -->
    <view class="func-card">
      <view class="func-row" @click="goEdit">
        <text class="func-title">编辑资料</text>
        <text class="arrow">›</text>
      </view>
      <view class="func-row" @click="goChangePassword">
        <text class="func-title">账号安全</text>
        <text class="arrow">›</text>
      </view>
      <view class="func-row" @click="goSupport">
        <text class="func-title">客服与帮助</text>
        <text class="arrow">›</text>
      </view>
      <view class="func-row" @click="showAgreementSheet = true">
        <text class="func-title">用户协议与隐私</text>
        <text class="arrow">›</text>
      </view>
      <view class="func-row func-row--danger" @click="handleLogout">
        <text class="func-title">退出登录</text>
      </view>
    </view>

    <!-- 协议选择 -->
    <view v-if="showAgreementSheet" class="modal-mask" @click.self="showAgreementSheet = false">
      <view class="sheet">
        <view class="sheet-title">用户协议与隐私</view>
        <view v-for="item in agreementList" :key="item.key" class="sheet-item" @click="chooseAgreement(item.key)">
          {{ item.label }}
        </view>
        <view class="sheet-cancel" @click="showAgreementSheet = false">取消</view>
      </view>
    </view>

    <view class="footer-space" />
  </view>
</template>

<script setup>
import { ref, computed } from 'vue';
import { onShow, onUnload } from '@dcloudio/uni-app';
import { useUserStore } from '@/store/user';
import { LEVEL_META, categoryLabel } from '@/common/constants';

const userStore = useUserStore();
const user = computed(() => userStore.user);

const level = computed(() => LEVEL_META[user.value?.level] || LEVEL_META.normal);
const levelStyle = computed(() => ({
  color: level.value.color,
  borderColor: level.value.color,
  backgroundColor: level.value.color + '1A',
}));

const qualifications = computed(() => (user.value?.qualifications || '').split('\n').filter(Boolean));
const cases = computed(() => (user.value?.cases || '').split('\n').filter(Boolean));

const funcList = [
  { title: '积分中心', action: 'points' },
  { title: '会员等级', action: 'level' },
  { title: '信用分', action: 'credit' },
  { title: '邀请好友', action: 'invite' },
  { title: '排行榜', action: 'ranking' },
  { title: '通知中心', action: 'notify' },
  { title: '提醒中心', action: 'reminder' },
  { title: '我的订单', action: 'orders' },
];

let shown = false;
const showAgreementSheet = ref(false);

const agreementList = [
  { key: 'agreement', label: '用户协议' },
  { key: 'privacy', label: '隐私政策' },
  { key: 'summary', label: '平台须知' },
];

onShow(() => {
  if (userStore.isAuthenticated && !shown) {
    userStore.fetchMe().catch(() => {});
  }
  shown = true;
});

function goPoints() {
  uni.navigateTo({ url: '/pages/points/index' });
}

function onFunc(item) {
  const map = {
    points: '/pages/points/index',
    level: '/pages/community/level',
    credit: '/pages/community/credit',
    invite: '/pages/community/invite',
    ranking: '/pages/community/ranking',
    notify: '/pages/community/notify',
    reminder: '/pages/community/reminder',
    orders: '/pages/order/list',
  };
  const url = map[item.action];
  if (url) uni.navigateTo({ url });
}

function goEdit() {
  uni.navigateTo({ url: '/pages/profile/edit' });
}

function goChangePassword() {
  uni.navigateTo({ url: '/pages/profile/change-password' });
}

function goSupport() {
  uni.navigateTo({ url: '/pages/common/support' });
}

function chooseAgreement(type) {
  showAgreementSheet.value = false;
  uni.navigateTo({ url: `/pages/common/agreement?type=${type}` });
}

function handleLogout() {
  uni.showModal({
    title: '退出登录',
    content: '确认退出当前账号？',
    success: (res) => {
      if (res.confirm) {
        userStore.logout();
      }
    },
  });
}
</script>

<style lang="scss" scoped>
.profile-page {
  min-height: 100vh;
}

.profile-card {
  display: flex;
  align-items: center;
  padding: 48rpx 32rpx;
  background: linear-gradient(135deg, #048C47, #06A85A);
}

.avatar {
  width: 100rpx;
  height: 100rpx;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.9);
  color: #048C47;
  font-size: 44rpx;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 24rpx;
}

.profile-info {
  flex: 1;
}

.profile-name {
  font-size: 34rpx;
  font-weight: 600;
  color: #ffffff;
}

.level-tag {
  display: inline-block;
  margin-top: 8rpx;
  padding: 4rpx 16rpx;
  border-radius: 20rpx;
  font-size: 22rpx;
}

.credit {
  font-size: 26rpx;
  color: #E4F7EC;
}

.credit-val {
  font-size: 32rpx;
  font-weight: 700;
}

.profile-meta {
  margin: 16rpx 24rpx;
  background: #ffffff;
  border-radius: 16rpx;
  padding: 8rpx 24rpx;
}

.meta-item {
  display: flex;
  align-items: center;
  padding: 20rpx 0;
  border-bottom: 1px solid #F2F4F5;
}

.meta-item:last-child {
  border-bottom: none;
}

.meta-item--link {
  justify-content: space-between;
}

.meta-label {
  width: 160rpx;
  font-size: 26rpx;
  color: #7A7A7A;
}

.meta-value {
  flex: 1;
  font-size: 26rpx;
  color: #1A1A1A;
  text-align: right;
}

.points-num {
  display: flex;
  align-items: center;
}

.points-val {
  font-size: 28rpx;
  font-weight: 600;
  color: #048C47;
}

.arrow {
  margin-left: 8rpx;
  color: #B0B0B0;
  font-size: 32rpx;
}

.section-card,
.func-card {
  margin: 16rpx 24rpx;
  background: #ffffff;
  border-radius: 16rpx;
  padding: 20rpx 24rpx;
}

.section-title {
  font-size: 28rpx;
  font-weight: 600;
  color: #1A1A1A;
  margin-bottom: 12rpx;
}

.qualification-item {
  display: flex;
  align-items: flex-start;
  padding: 8rpx 0;
}

.section-mark {
  color: #048C47;
  font-size: 24rpx;
  margin-right: 12rpx;
  margin-top: 4rpx;
}

.qualification-text,
.case-text {
  flex: 1;
  font-size: 26rpx;
  color: #4A4A4A;
  line-height: 1.5;
}

.case-card {
  background: #F8FAF9;
  border-radius: 12rpx;
  padding: 16rpx;
  margin-bottom: 12rpx;
}

.case-card:last-child {
  margin-bottom: 0;
}

.func-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24rpx 0;
  border-bottom: 1px solid #F2F4F5;
}

.func-row:last-child {
  border-bottom: none;
}

.func-title {
  font-size: 28rpx;
  color: #1A1A1A;
}

.func-row--danger .func-title {
  color: #E54848;
}

.footer-space {
  height: 40rpx;
}

.modal-mask {
  position: fixed;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  z-index: 200;
  display: flex;
  align-items: flex-end;
}

.sheet {
  width: 100%;
  background: #ffffff;
  border-radius: 24rpx 24rpx 0 0;
  padding-bottom: env(safe-area-inset-bottom);
}

.sheet-title {
  text-align: center;
  padding: 24rpx;
  font-size: 30rpx;
  font-weight: 600;
  color: #1A1A1A;
  border-bottom: 1px solid #F2F4F5;
}

.sheet-item {
  text-align: center;
  padding: 28rpx;
  font-size: 28rpx;
  color: #1A1A1A;
  border-bottom: 1px solid #F7F8F9;
}

.sheet-item:active {
  background: #F8FAF9;
}

.sheet-cancel {
  text-align: center;
  padding: 28rpx;
  font-size: 28rpx;
  color: #7A7A7A;
}
</style>
