// archive/client/src/pages/Credit.jsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Toast, Cell, CellGroup, Progress, Empty, PullRefresh } from 'react-vant';
import { api } from '../api';
import PageNavBar from '../components/PageNavBar';
import Pagination from '../components/Pagination';
import { timeAgo } from '../constants';

const CHANGE_LABELS = {
  invalid_mark: '商机被判无效',
  share_report: '分享被举报',
  account_report: '账号被举报',
  purchase: '购买商机',
  share_helpful: '分享被认可',
  weekly_active: '活跃奖励',
  admin_adjust: '管理员调整',
};

export default function Credit() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [page, setPage] = useState(1);
  const pageSize = 6;

  const fetchLogs = async () => {
    const res = await api.credits({ page: 1, pageSize: 50 });
    setLogs(res.list || []);
    return res;
  };

  useEffect(() => {
    Promise.all([api.me(), fetchLogs()])
      .then(([me]) => setUser(me))
      .catch((e) => Toast.fail(e.message))
      .finally(() => setLoading(false));
  }, []);

  const onRefresh = async () => {
    setRefreshing(true);
    try {
      const [me] = await Promise.all([api.me(), fetchLogs()]);
      setUser(me);
      Toast.success('已刷新');
    } catch (e) {
      Toast.fail(e.message);
    } finally {
      setRefreshing(false);
    }
  };

  if (loading) return <div className="page"><PageNavBar title="信用分" onClickLeft={() => navigate(-1)} /><div className="empty-tip">加载中...</div></div>;

  const score = user?.creditScore ?? 100;
  const tone = score >= 80 ? 'success' : score >= 60 ? 'warning' : 'danger';
  const colorVar = `var(--${tone}-color)`;
  const label = score >= 80 ? '信用良好' : score >= 60 ? '信用一般' : '信用较差';

  return (
    <div className="page">
      <PageNavBar title="信用分" onClickLeft={() => navigate(-1)} />

      {/* 信用分卡片 */}
      <div className="credit-card">
        <div className="credit-card__score" style={{ color: colorVar }}>{score}</div>
        <div className="credit-card__label">{label}</div>
        <Progress percentage={score} color={colorVar} className="credit-progress" />
      </div>

      {/* 变动记录 */}
      <div className="section-title section-title--pad">信用分记录</div>
      <PullRefresh onRefresh={onRefresh} refreshing={refreshing}>
        {logs.length === 0 ? (
          <Empty description="暂无信用分变动记录" className="empty-top" />
        ) : (() => {
          const totalPages = Math.ceil(logs.length / pageSize);
          const visible = logs.slice((page - 1) * pageSize, page * pageSize);
          return (
            <CellGroup inset className="profile-section--gap">
              {visible.map((log) => (
                <Cell
                  key={log.id}
                  title={log.reason || CHANGE_LABELS[log.sourceType] || '信用分变动'}
                  label={timeAgo(log.createdAt)}
                  value={
                    <span className={`credit-delta ${log.changeAmount >= 0 ? 'text-success' : 'text-danger'}`}>
                      {log.changeAmount >= 0 ? `+${log.changeAmount}` : log.changeAmount}
                    </span>
                  }
                />
              ))}
              {totalPages > 1 && (
                <Pagination page={page} totalPages={totalPages} onChange={setPage} />
              )}
            </CellGroup>
          );
        })()}
      </PullRefresh>

      {/* 说明 */}
      <CellGroup inset className="profile-section--gap">
        <Cell title="信用分说明" label="初始100分，根据您的行为动态调整" />
        <Cell title="80分以上" label="正常使用所有功能" />
        <Cell title="60-80分" label="投稿商机需要审核才能上架" />
        <Cell title="40-60分" label="禁止投稿，只能购买和跟进" />
        <Cell title="40分以下" label="账号封禁" />
      </CellGroup>
    </div>
  );
}

// miniapp/src/pages/community/credit.vue
<template>
  <view class="credit-page">
    <view v-if="loading" class="empty">加载中...</view>
    <template v-else>
      <!-- 信用分卡片 -->
      <view class="credit-card">
        <view class="credit-card__score" :style="{ color: scoreColor }">{{ score }}</view>
        <view class="credit-card__label">{{ scoreLabel }}</view>
        <view class="credit-track">
          <view class="credit-track__bar" :style="{ width: score + '%', background: scoreColor }"></view>
        </view>
      </view>

      <!-- 变动记录 -->
      <view class="section-title">信用分记录</view>
      <view class="section-card">
        <view v-if="!logs.length" class="empty">暂无信用分变动记录</view>
        <view v-else class="log-list">
          <view v-for="log in visibleLogs" :key="log.id" class="log-item">
            <view class="log-info">
              <view class="log-reason">{{ log.reason || CHANGE_LABELS[log.sourceType] || '信用分变动' }}</view>
              <view class="log-time">{{ timeAgo(log.createdAt) }}</view>
            </view>
            <text
              class="log-delta"
              :class="log.changeAmount >= 0 ? 'log-delta--up' : 'log-delta--down'"
            >
              {{ log.changeAmount >= 0 ? `+${log.changeAmount}` : log.changeAmount }}
            </text>
          </view>
        </view>
        <view v-if="totalPages > 1" class="pager">
          <view
            class="pager-btn"
            :class="{ disabled: page <= 1 }"
            @click="changePage(page - 1)"
          >上一页</view>
          <view class="pager-info">{{ page }} / {{ totalPages }}</view>
          <view
            class="pager-btn"
            :class="{ disabled: page >= totalPages }"
            @click="changePage(page + 1)"
          >下一页</view>
        </view>
      </view>

      <!-- 说明 -->
      <view class="section-title">信用分说明</view>
      <view class="section-card">
        <view class="rule-row"><text class="rule-text">信用分说明</text><text class="rule-desc">初始 100 分，根据您的行为动态调整</text></view>
        <view class="rule-row"><text class="rule-text">80 分以上</text><text class="rule-desc">正常使用所有功能</text></view>
        <view class="rule-row"><text class="rule-text">60-80 分</text><text class="rule-desc">投稿商机需要审核才能上架</text></view>
        <view class="rule-row"><text class="rule-text">40-60 分</text><text class="rule-desc">禁止投稿，只能购买和跟进</text></view>
        <view class="rule-row"><text class="rule-text">40 分以下</text><text class="rule-desc">账号封禁</text></view>
      </view>
    </template>
  </view>
</template>

<script setup>
import { ref, computed } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api } from '@/api/index';
import { timeAgo } from '@/common/constants';

const CHANGE_LABELS = {
  invalid_mark: '商机被判无效',
  share_report: '分享被举报',
  account_report: '账号被举报',
  purchase: '购买商机',
  share_helpful: '分享被认可',
  weekly_active: '活跃奖励',
  admin_adjust: '管理员调整',
};

const loading = ref(true);
const score = ref(100);
const logs = ref([]);
const page = ref(1);
const pageSize = 6;

onLoad(() => {
  Promise.all([api.me(), fetchLogs()])
    .then(([me]) => {
      score.value = me?.creditScore ?? 100;
    })
    .catch(() => {})
    .finally(() => {
      loading.value = false;
    });
});

async function fetchLogs() {
  const res = await api.credits({ page: 1, pageSize: 50 });
  logs.value = res?.list || [];
  return res;
}

const totalPages = computed(() => Math.ceil(logs.value.length / pageSize));
const visibleLogs = computed(() => {
  const start = (page.value - 1) * pageSize;
  return logs.value.slice(start, start + pageSize);
});

const scoreColor = computed(() => {
  const s = score.value;
  return s >= 80 ? '#048C47' : s >= 60 ? '#E8920A' : '#E54848';
});

const scoreLabel = computed(() => {
  const s = score.value;
  return s >= 80 ? '信用良好' : s >= 60 ? '信用一般' : '信用较差';
});

function changePage(p) {
  if (p < 1 || p > totalPages.value) return;
  page.value = p;
}
</script>

<style lang="scss" scoped>
.credit-page {
  min-height: 100vh;
}

.empty {
  text-align: center;
  padding: 80rpx 0;
  color: #B0B0B0;
  font-size: 28rpx;
}

.credit-card {
  margin: 24rpx;
  background: #ffffff;
  border-radius: 16rpx;
  padding: 48rpx 40rpx 40rpx;
  text-align: center;
}

.credit-card__score {
  font-size: 72rpx;
  font-weight: 700;
}

.credit-card__label {
  margin-top: 8rpx;
  font-size: 28rpx;
  color: #4A4A4A;
}

.credit-track {
  margin-top: 24rpx;
  height: 12rpx;
  border-radius: 6rpx;
  background: #F2F4F5;
  overflow: hidden;
}

.credit-track__bar {
  height: 100%;
  border-radius: 6rpx;
}

.section-title {
  margin: 8rpx 32rpx 16rpx;
  font-size: 28rpx;
  font-weight: 600;
  color: #1A1A1A;
}

.section-card {
  margin: 0 24rpx 16rpx;
  background: #ffffff;
  border-radius: 16rpx;
  padding: 24rpx;
}

.log-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 18rpx 0;
  border-bottom: 1px solid #F2F4F5;
}

.log-item:last-child {
  border-bottom: none;
}

.log-reason {
  font-size: 26rpx;
  color: #1A1A1A;
}

.log-time {
  margin-top: 6rpx;
  font-size: 22rpx;
  color: #B0B0B0;
}

.log-delta {
  font-size: 28rpx;
  font-weight: 600;
}

.log-delta--up {
  color: #048C47;
}

.log-delta--down {
  color: #E54848;
}

.pager {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24rpx 0 8rpx;
}

.pager-btn {
  padding: 10rpx 32rpx;
  border-radius: 8rpx;
  border: 1px solid #048C47;
  color: #048C47;
  font-size: 24rpx;
}

.pager-btn.disabled {
  opacity: 0.4;
}

.pager-info {
  margin: 0 24rpx;
  font-size: 24rpx;
  color: #7A7A7A;
}

.rule-row {
  padding: 12rpx 0;
}

.rule-text {
  font-size: 26rpx;
  color: #1A1A1A;
  font-weight: 600;
}

.rule-desc {
  display: block;
  margin-top: 4rpx;
  font-size: 24rpx;
  color: #7A7A7A;
}
</style>
